
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 13 10:41:00 COT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUMANDO = 3;
  public static final int ENTERO = 8;
  public static final int EOF = 0;
  public static final int PARENIZQ = 6;
  public static final int error = 1;
  public static final int PUNTOCOMA = 2;
  public static final int PARENDER = 7;
  public static final int RESTANDO = 4;
  public static final int MULTIPLICANDO = 5;
}

